/* ==========================================================
   FAME — how well known each animal is. GENERATED from data/animals.xlsx (column "Fame")
   by tools/animal_data.py. DO NOT EDIT: change the Excel sheet and run the build.
     1 = Familiar  (nearly everyone can picture it)
     2 = Known     (most people have heard of it)
     3 = Obscure   (many players will have to think, or won't know it)
   Sets animal.fame on every entry of ALL_ANIMALS. Depends on: animals.js
   ========================================================== */

var FAME = {
  "Lion": 1,
  "Tiger": 1,
  "Leopard": 1,
  "Cheetah": 1,
  "Jaguar": 2,
  "Snow Leopard": 2,
  "African Elephant": 1,
  "Giraffe": 1,
  "Zebra": 1,
  "Hippopotamus": 1,
  "White Rhinoceros": 1,
  "Spotted Hyena": 2,
  "Meerkat": 1,
  "Ring-tailed Lemur": 2,
  "Dromedary Camel": 2,
  "Gorilla": 1,
  "Chimpanzee": 1,
  "Orangutan": 2,
  "Giant Panda": 1,
  "Polar Bear": 1,
  "Walrus": 2,
  "Reindeer": 2,
  "Grizzly Bear": 1,
  "Gray Wolf": 1,
  "Moose": 1,
  "American Bison": 2,
  "Bighorn Sheep": 3,
  "Gray Squirrel": 1,
  "Beaver": 1,
  "Raccoon": 2,
  "Striped Skunk": 2,
  "Little Brown Bat": 3,
  "Harbor Seal": 2,
  "Red Fox": 1,
  "Wild Boar": 2,
  "European Hedgehog": 2,
  "Red Kangaroo": 1,
  "Koala": 1,
  "Platypus": 2,
  "Three-toed Sloth": 1,
  "Capybara": 2,
  "Giant Anteater": 2,
  "Nine-banded Armadillo": 2,
  "Tapir": 3,
  "Bottlenose Dolphin": 1,
  "Blue Whale": 1,
  "Orca": 1,
  "Bald Eagle": 1,
  "Crow": 1,
  "Woodpecker": 2,
  "Mallard Duck": 2,
  "Barn Owl": 2,
  "House Sparrow": 2,
  "Mute Swan": 2,
  "Atlantic Puffin": 2,
  "Ostrich": 1,
  "Flamingo": 1,
  "Vulture": 2,
  "Peacock": 1,
  "Toucan": 1,
  "Hummingbird": 1,
  "Scarlet Macaw": 1,
  "Kiwi": 2,
  "Emperor Penguin": 1,
  "Wandering Albatross": 3,
  "Nile Crocodile": 1,
  "Chameleon": 1,
  "American Alligator": 1,
  "Rattlesnake": 1,
  "Komodo Dragon": 1,
  "King Cobra": 1,
  "Burmese Python": 2,
  "Tokay Gecko": 3,
  "Green Iguana": 2,
  "Galapagos Tortoise": 1,
  "Green Sea Turtle": 1,
  "Bearded Dragon": 2,
  "American Bullfrog": 2,
  "Axolotl": 2,
  "Fire Salamander": 3,
  "Chinese Giant Salamander": 3,
  "Poison Dart Frog": 2,
  "Red-eyed Tree Frog": 2,
  "Cane Toad": 2,
  "Great White Shark": 1,
  "Whale Shark": 2,
  "Manta Ray": 2,
  "Swordfish": 2,
  "Seahorse": 2,
  "Pufferfish": 2,
  "Clownfish": 1,
  "Goldfish": 1,
  "Atlantic Salmon": 1,
  "Piranha": 2,
  "Electric Eel": 2,
  "Honeybee": 1,
  "Ladybug": 1,
  "Garden Snail": 1,
  "Earthworm": 1,
  "Dragonfly": 2,
  "Monarch Butterfly": 1,
  "Blue Crab": 1,
  "American Lobster": 1,
  "Praying Mantis": 2,
  "Emperor Scorpion": 3,
  "Leafcutter Ant": 3,
  "Tarantula": 1,
  "Common Octopus": 1,
  "Giant Squid": 3,
  "Moon Jellyfish": 2,
  "Starfish": 1,
  "Asian Elephant": 2,
  "Cougar": 2,
  "Canada Lynx": 3,
  "Ocelot": 3,
  "American Black Bear": 2,
  "Coyote": 2,
  "Arctic Fox": 2,
  "African Wild Dog": 3,
  "Wildebeest": 2,
  "Impala": 3,
  "Cape Buffalo": 3,
  "Okapi": 3,
  "Olive Baboon": 3,
  "Fennec Fox": 2,
  "Aardvark": 3,
  "Pangolin": 3,
  "Red Panda": 2,
  "Yak": 2,
  "Sea Otter": 2,
  "River Otter": 2,
  "Manatee": 2,
  "California Sea Lion": 2,
  "Mountain Goat": 3,
  "Pronghorn": 3,
  "White-tailed Deer": 2,
  "Virginia Opossum": 2,
  "Narwhal": 2,
  "Humpback Whale": 2,
  "Llama": 2,
  "European Rabbit": 2,
  "European Badger": 3,
  "Tasmanian Devil": 2,
  "Wombat": 3,
  "Short-beaked Echidna": 3,
  "Dingo": 3,
  "Peregrine Falcon": 3,
  "Great Horned Owl": 2,
  "Snowy Owl": 2,
  "Blue Jay": 2,
  "Northern Cardinal": 2,
  "Wild Turkey": 1,
  "Roadrunner": 2,
  "Canada Goose": 1,
  "Brown Pelican": 2,
  "Blue-footed Booby": 3,
  "Harpy Eagle": 3,
  "European Robin": 3,
  "Hornbill": 3,
  "Cassowary": 3,
  "Emu": 2,
  "Kookaburra": 3,
  "Gharial": 3,
  "Green Anaconda": 2,
  "Black Mamba": 2,
  "Nile Monitor": 3,
  "Leopard Tortoise": 3,
  "Gila Monster": 3,
  "Common Snapping Turtle": 2,
  "Garter Snake": 2,
  "Marine Iguana": 3,
  "European Common Frog": 3,
  "Tiger Salamander": 3,
  "Hellbender": 3,
  "Goliath Frog": 3,
  "White's Tree Frog": 3,
  "Bluefin Tuna": 2,
  "Great Barracuda": 3,
  "Hammerhead Shark": 2,
  "Ocean Sunfish": 2,
  "Anglerfish": 2,
  "Moray Eel": 2,
  "Blue Tang": 2,
  "Lionfish": 2,
  "Rainbow Trout": 2,
  "Channel Catfish": 3,
  "Beluga Sturgeon": 3,
  "Arapaima": 3,
  "Desert Locust": 3,
  "Termite": 2,
  "Dung Beetle": 3,
  "Firefly": 2,
  "Black Widow Spider": 2,
  "Banana Slug": 3,
  "Horseshoe Crab": 3,
  "Stag Beetle": 3,
  "Mosquito": 1,
  "Sea Urchin": 2,
  "Chambered Nautilus": 3,
  "Mantis Shrimp": 3
};

ALL_ANIMALS.forEach(function (a) { a.fame = FAME[a.name] || 2; });
