#!/usr/bin/env python3
"""
Animaldle master data: data/animals.xlsx  <->  js/animals.js + js/fame.js

  python3 tools/animal_data.py build     Excel -> js/animals.js and js/fame.js (validates first)
  python3 tools/animal_data.py export    js files -> Excel (one-time / recovery; OVERWRITES the sheet)

The Excel file is the source of truth. Never hand-edit js/animals.js or js/fame.js:
they are regenerated by `build`. Needs: pip3 install openpyxl, and node (to read filters.js).
"""
import json, os, subprocess, sys
from openpyxl import Workbook, load_workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.utils import get_column_letter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
XLSX = os.path.join(ROOT, 'data', 'animals.xlsx')
TRAITS = ['wings', 'horns', 'tail', 'shell', 'stripes', 'spots', 'snout', 'trunk']
SINGLE = ['class', 'region', 'climate', 'habitat', 'environment', 'size', 'diet', 'activity', 'social', 'covering']
# (header, kind, key)
COLUMNS = ([('Name', 'name', 'name'), ('Fame (1-3)', 'fame', 'fame')]
           + [(k.capitalize(), 'single', k) for k in SINGLE]
           + [('Special diet', 'list', 'diet2'), ('Locomotion', 'list', 'locomotion')]
           + [('Has ' + t, 'trait', t) for t in TRAITS])
# Same header text the filter dropdowns use, for the reference sheet
LIST_KEYS = SINGLE + ['diet2', 'locomotion']
FAME_LABELS = {1: 'Familiar', 2: 'Known', 3: 'Obscure'}


def node(code):
    out = subprocess.run(['node', '-e', code], cwd=ROOT, capture_output=True, text=True)
    if out.returncode:
        sys.exit('node failed: ' + out.stderr)
    return json.loads(out.stdout)


def filter_options():
    """Allowed values per filter id, read from js/filters.js (the single place options are defined)."""
    return node("const fs=require('fs'),vm=require('vm');const c={};vm.createContext(c);"
                "vm.runInContext(fs.readFileSync('js/filters.js','utf8')+';this.F=FILTERS',c);"
                "const o={};c.F.forEach(f=>{if(f.kind!=='boolean')o[f.id]=f.options});console.log(JSON.stringify(o))")


def load_js_animals():
    return node("const fs=require('fs'),vm=require('vm');const c={};vm.createContext(c);"
                "for(const f of ['animals','fame'])vm.runInContext(fs.readFileSync('js/'+f+'.js','utf8'),c);"
                "console.log(JSON.stringify(vm.runInContext('ALL_ANIMALS',c)))")


# ---------------------------------------------------------------- export
def export_xlsx():
    animals = load_js_animals()
    opts = filter_options()
    wb = Workbook()
    ws = wb.active
    ws.title = 'Animals'
    ws.append([c[0] for c in COLUMNS])
    for a in animals:
        row = []
        for _, kind, key in COLUMNS:
            if kind == 'list':
                row.append(', '.join(a.get(key, [])))
            elif kind == 'trait':
                row.append('Yes' if key in a.get('traits', []) else '')
            else:
                row.append(a.get(key))
        ws.append(row)

    head = PatternFill('solid', fgColor='2F5D3A')
    for i, (h, _, _) in enumerate(COLUMNS, 1):
        c = ws.cell(1, i)
        c.font = Font(bold=True, color='FFFFFF')
        c.fill = head
        c.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)
        ws.column_dimensions[get_column_letter(i)].width = 14
    ws.column_dimensions['A'].width = 26
    ws.column_dimensions[get_column_letter([c[2] for c in COLUMNS].index('diet2') + 1)].width = 18
    ws.column_dimensions[get_column_letter([c[2] for c in COLUMNS].index('locomotion') + 1)].width = 24
    ws.row_dimensions[1].height = 32
    ws.freeze_panes = 'C2'
    ws.auto_filter.ref = ws.dimensions

    # Reference sheet: one column per filter listing allowed values (also feeds the dropdowns)
    ls = wb.create_sheet('Lists')
    ref = {}
    for i, k in enumerate(LIST_KEYS, 1):
        ls.cell(1, i, k.capitalize() if k != 'diet2' else 'Special diet').font = Font(bold=True)
        ls.column_dimensions[get_column_letter(i)].width = 16
        for j, v in enumerate(opts[k], 2):
            ls.cell(j, i, v)
        ref[k] = "Lists!$%s$2:$%s$%d" % (get_column_letter(i), get_column_letter(i), len(opts[k]) + 1)
    ls.cell(1, len(LIST_KEYS) + 2, 'Fame').font = Font(bold=True)
    for j, (n, lab) in enumerate(FAME_LABELS.items(), 2):
        ls.cell(j, len(LIST_KEYS) + 2, '%d = %s' % (n, lab))
    ls.cell(7, 1, 'These lists come from js/filters.js. To add a new allowed value, add it there AND here (validation only).')

    n = len(animals) + 500   # room for new animals
    keys = [c[2] for c in COLUMNS]
    for k in SINGLE:
        col = get_column_letter(keys.index(k) + 1)
        dv = DataValidation(type='list', formula1='=' + ref[k], allow_blank=True, showErrorMessage=True)
        ws.add_data_validation(dv)
        dv.add('%s2:%s%d' % (col, col, n))
    col = get_column_letter(keys.index('fame') + 1)
    dv = DataValidation(type='whole', operator='between', formula1='1', formula2='3', allow_blank=False, showErrorMessage=True)
    ws.add_data_validation(dv)
    dv.add('%s2:%s%d' % (col, col, n))
    for t in TRAITS:
        col = get_column_letter(keys.index(t) + 1)
        dv = DataValidation(type='list', formula1='"Yes"', allow_blank=True, showErrorMessage=True)
        ws.add_data_validation(dv)
        dv.add('%s2:%s%d' % (col, col, n))

    rd = wb.create_sheet('READ ME', 0)
    for line in [
        'Animaldle master data — this workbook is the single source of truth.',
        '',
        'Edit the "Animals" sheet: one row per animal, one column per filter.',
        '  • Fame: 1 = Familiar, 2 = Known, 3 = Obscure (drives the difficulty mix).',
        '  • Single-value columns have dropdowns. Values must match the Lists sheet exactly.',
        '  • Special diet / Locomotion: comma-separated. Locomotion: the FIRST entry is the primary way of moving.',
        '    Special diet may be blank (no special diet).',
        '  • Has ... columns: "Yes" or blank.',
        '  • Row order = order in the game files; groups are labelled by class automatically.',
        '  • Renaming an animal breaks its photo link (photos are keyed by name) — the build warns about this.',
        '',
        'After editing, save the file and run:',
        '    python3 tools/animal_data.py build',
        'That validates everything, then regenerates js/animals.js and js/fame.js. Do not hand-edit those files.',
    ]:
        rd.append([line])
    rd.column_dimensions['A'].width = 110
    rd['A1'].font = Font(bold=True, size=13)

    os.makedirs(os.path.dirname(XLSX), exist_ok=True)
    wb.save(XLSX)
    print('Wrote %s (%d animals)' % (XLSX, len(animals)))


# ---------------------------------------------------------------- build
def split(s):
    return [p.strip() for p in str(s or '').split(',') if p.strip()]


def build_js():
    opts = filter_options()
    wb = load_workbook(XLSX, data_only=True)
    ws = wb['Animals']
    header = [c.value for c in ws[1]]
    expected = [c[0] for c in COLUMNS]
    if header[:len(expected)] != expected:
        sys.exit('Animals sheet headers changed. Expected: %s' % expected)
    animals, errors, seen = [], [], set()
    for r, row in enumerate(ws.iter_rows(min_row=2, values_only=True), 2):
        if not any(v not in (None, '') for v in row):
            continue
        d = dict(zip([c[2] for c in COLUMNS], row))
        name = str(d['name'] or '').strip()
        if not name:
            errors.append('row %d: missing name' % r); continue
        if name in seen:
            errors.append('row %d: duplicate name "%s"' % (r, name))
        seen.add(name)
        a = {'name': name}
        try:
            a['fame'] = int(d['fame'])
            assert a['fame'] in (1, 2, 3)
        except Exception:
            errors.append('row %d %s: Fame must be 1, 2 or 3 (got %r)' % (r, name, d['fame'])); a['fame'] = 2
        for k in SINGLE:
            v = str(d[k] or '').strip()
            if v not in opts[k]:
                errors.append('row %d %s: %s "%s" is not one of %s' % (r, name, k, v, opts[k]))
            a[k] = v
        for k in ('diet2', 'locomotion'):
            vals = split(d[k])
            bad = [v for v in vals if v not in opts[k]]
            if bad:
                errors.append('row %d %s: %s has unknown %s (allowed: %s)' % (r, name, k, bad, opts[k]))
            a[k] = vals
        if not a['locomotion']:
            errors.append('row %d %s: Locomotion needs at least one value' % (r, name))
        a['traits'] = [t for t in TRAITS if str(d[t] or '').strip().lower() == 'yes']
        animals.append(a)
    if errors:
        print('NOT BUILT — %d problem(s):' % len(errors))
        for e in errors:
            print('  ' + e)
        sys.exit(1)

    # Warn about photo links that no longer resolve
    photos = node("const fs=require('fs'),vm=require('vm');const c={};vm.createContext(c);"
                  "vm.runInContext(fs.readFileSync('js/photos.js','utf8'),c);console.log(JSON.stringify(Object.keys(c.PHOTOS)))")
    orphan = [n for n in photos if n not in seen]
    missing = [a['name'] for a in animals if a['name'] not in photos]
    if orphan:
        print('WARNING: photos exist for names not in the sheet (renamed or removed?): %s' % orphan)
    if missing:
        print('note: %d animal(s) have no photo yet and won\'t be playable while REQUIRE_PHOTO is on: %s' % (len(missing), missing))

    write_animals_js(animals)
    write_fame_js(animals)
    print('Built js/animals.js and js/fame.js from %d animals.' % len(animals))


def q(s):
    return json.dumps(s, ensure_ascii=False)


def write_animals_js(animals):
    L = ['/* ==========================================================',
         '   ANIMAL DATABASE — GENERATED from data/animals.xlsx by tools/animal_data.py.',
         '   DO NOT EDIT THIS FILE: change the Excel sheet and run',
         '       python3 tools/animal_data.py build',
         '   Fields:',
         '     class, region, climate, habitat, size, diet, activity, social, covering, environment: single value',
         '     diet2      : optional array of secondary diets (Insectivore / Piscivore / Frugivore)',
         '     locomotion : array; FIRST entry is the primary way of moving',
         '     traits     : array from: wings, horns, tail, shell, stripes, spots, snout, trunk',
         '   Allowed values are listed in filters.js. Fame ratings are in fame.js.',
         '   This is the FULL database. Which animals are actually playable is decided in roster.js.',
         '   ========================================================== */',
         'var ALL_ANIMALS = [']
    last = None
    for i, a in enumerate(animals):
        if a['class'] != last:
            last = a['class']
            L.append('  // ---------- %sS ----------' % last.upper())
        parts = ['name:' + q(a['name'])]
        for k in SINGLE:
            parts.append('%s:%s' % (k, q(a[k])))
        if a['diet2']:
            parts.append('diet2:' + q(a['diet2']))
        parts.append('locomotion:' + q(a['locomotion']))
        parts.append('traits:' + q(a['traits']))
        L.append('  { ' + ', '.join(parts) + ' }' + (',' if i < len(animals) - 1 else ''))
    L.append('];')
    open(os.path.join(ROOT, 'js', 'animals.js'), 'w').write('\n'.join(L).replace('","', '","') + '\n')


def write_fame_js(animals):
    L = ['/* ==========================================================',
         '   FAME — how well known each animal is. GENERATED from data/animals.xlsx (column "Fame")',
         '   by tools/animal_data.py. DO NOT EDIT: change the Excel sheet and run the build.',
         '     1 = Familiar  (nearly everyone can picture it)',
         '     2 = Known     (most people have heard of it)',
         '     3 = Obscure   (many players will have to think, or won\'t know it)',
         '   Sets animal.fame on every entry of ALL_ANIMALS. Depends on: animals.js',
         '   ========================================================== */',
         '',
         'var FAME = {']
    for i, a in enumerate(animals):
        L.append('  %s: %d%s' % (q(a['name']), a['fame'], ',' if i < len(animals) - 1 else ''))
    L += ['};', '',
          'ALL_ANIMALS.forEach(function (a) { a.fame = FAME[a.name] || 2; });']
    open(os.path.join(ROOT, 'js', 'fame.js'), 'w').write('\n'.join(L) + '\n')


if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else 'build'
    if cmd == 'export':
        export_xlsx()
    elif cmd == 'build':
        build_js()
    else:
        sys.exit(__doc__)
