// Builds js/photos.js — the game's photo manifest — from images/images.json.
//   node tools/build-photos.mjs
// An animal is "approved" (playable when REQUIRE_PHOTO is on) if it has an image whose licence
// is status "ok" (public domain / CC0 / CC BY / CC BY-SA) and no note in tools/manual-notes.json.
// Run automatically by fetch-images.mjs and set-image.mjs.
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const recs = JSON.parse(fs.readFileSync(path.join(ROOT, 'images/images.json'), 'utf8'));
const notesPath = path.join(ROOT, 'tools/manual-notes.json');
const manual = fs.existsSync(notesPath) ? JSON.parse(fs.readFileSync(notesPath, 'utf8')) : {};

const clip = (s, n) => (s.length > n ? s.slice(0, n - 1).trimEnd() + '…' : s);
const photos = {};
let approved = 0;
for (const r of recs.slice().sort((a, b) => a.animal.localeCompare(b.animal))) {
  if (!r.localFile) continue;
  const ok = r.status === 'ok' && !manual[r.animal];
  if (ok) approved++;
  photos[r.animal] = {
    file: r.localFile,
    author: clip(r.author || 'Unknown', 80),
    license: r.license || '',
    licenseUrl: r.licenseUrl || '',
    source: r.sourceUrl || '',
    approved: ok,
  };
}
const body = Object.entries(photos).map(([k, v]) => '  ' + JSON.stringify(k) + ': ' + JSON.stringify(v)).join(',\n');
fs.writeFileSync(path.join(ROOT, 'js/photos.js'),
`/* ==========================================================
   PHOTO MANIFEST — GENERATED by tools/build-photos.mjs. Do not edit by hand.
   approved:true  = licence ok and no known picture problem (playable when REQUIRE_PHOTO is on)
   ========================================================== */
var PHOTOS = {
${body}
};
`);
console.log(`js/photos.js: ${Object.keys(photos).length} photos, ${approved} approved`);
